# letsencrypt requires latest version of various python modules, hence
# We will run in a virtual environment of python3
- name: Install virtualenv
  yum:
    name: python-virtualenv 
    state: present
  become: yes

- name: Create python3 virtual environment
  command:
    cmd: virtualenv {{ansible_env.HOME}}/.venv-py3 -p python3
    creates: "{{ansible_env.HOME}}/.venv-py3/bin/pip"

- name: Upgrade pip to latest
  command: '{{ansible_env.HOME}}/.venv-py3/bin/pip install --upgrade pip'

#install specific cryptography version since >3.4 releases have rust dependency that throws an error.
- name: Install certbot in python3 virtual environment 
  pip:
    name: 
      - cryptography==3.3.2
      - 'certbot=={{certbot_version}}'
    virtualenv_python: python3
    virtualenv: '{{ansible_env.HOME}}/.venv-py3'
    state: present

- name: Install certbot-nginx
  pip:
    name: certbot-nginx
    version: '{{certbot_nginx_version}}' 
    virtualenv: '{{ansible_env.HOME}}/.venv-py3'
    state: present

- name: Comment import IO in certbot/crypto_util.py
  replace:
    path: '{{ansible_env.HOME}}/.venv-py3/lib/python3.6/site-packages/certbot/crypto_util.py'
    regexp: 'from acme.magic_typing import IO'
    replace: '#from acme.magic_typing import IO'
    backup: yes

# The below code section has been added to automate the process of Challenge Verification with Certbot and CloudFlare since our domain name points to a private IP Address. You should replace the values [YOUREMAIL, YOURAPIKEY] with your own values.
# If your domain name points to a public IP Address, then you can skip this step by commenting out line 46-54, line 57 and uncommenting line 56.

- name: Install Certbot Cloudflare Plugin
  pip:
    name: certbot-dns-cloudflare
    virtualenv: '{{ansible_env.HOME}}/.venv-py3'
    state: present

- name: Configure Certbot Cloudflare Plugin Files
  become: yes
  shell: mkdir /home/mosipuser/.secrets/ && touch /home/mosipuser/.secrets/cloudflare.ini && echo "dns_cloudflare_email = YOUREMAIL" >> /home/mosipuser/.secrets/cloudflare.ini && echo "dns_cloudflare_api_key = YOURAPIKEY" >> /home/mosipuser/.secrets/cloudflare.ini && sudo chmod 0700 /home/mosipuser/.secrets/ && sudo chmod 0400 /home/mosipuser/.secrets/cloudflare.ini

- name: run certbot 
  #shell: '{{ansible_env.HOME}}/.venv-py3/bin/certbot certonly --nginx -n  -m "{{ssl.ca.letsencrypt.email}}" --agree-tos -d {{ item }} '
  shell: '{{ansible_env.HOME}}/.venv-py3/bin/certbot certonly -i nginx -n -m "{{ssl.ca.letsencrypt.email}}" --agree-tos --dns-cloudflare --dns-cloudflare-credentials /home/mosipuser/.secrets/cloudflare.ini --dns-cloudflare-propagation-seconds 60 -d mosipcmuafrica.me,*.mosipcmuafrica.me --preferred-challenges dns-01'
  become: yes
  register: out
  with_items:
    - "{{sandbox_domain_name}}"
    # add more sub-domains - should exist in DNS records.
    #- "api.{{sandbox_domain_name}}"

- debug:
    msg: '{{out}}'

